// frontend-react/src/components/PxMain/PxSocialDataUser.js
import React from 'react';
// import getUser from '../../apiCore';

const PxSocialDataUser = props => {
  const userSocialNetwork = props.socialNetwork[0];
  const dataUser = props.socialNetwork[1];

  return (
    <article className={ `socialData ${userSocialNetwork}` }>
      <div className="socialData__topLiner"></div>

      <section className="socialData__socialNetworkUser">
        <img src="" alt="socialIcon" />
        <span>@{ dataUser.userName }</span>
      </section>

      <section className="socialData__followersUser">
        <img src="" alt="socialIcon" />
        <span>{ dataUser.followers }</span>
        <small>follower</small>
      </section>

      <section className="socialData__dataFollowers">
        <span>{ dataUser.followersToday } Today</span>
      </section>
    </article>
  )
}

export default PxSocialDataUser;

// frontend-vue/src/components/PxSocialDataUser.vue
<template>
  <article class='socialData'>
    <div class="socialData__topLiner"></div>

    <section class="socialData__socialNetworkUser">
      <img src="" alt="socialIcon" />
      <span>@{{ socialNetworkDataUser.userName }}</span>
    </section>

    <section class="socialData__followersUser">
      <img src="" alt="socialIcon" />
      <span>{{ socialNetworkDataUser.followers }}</span>
      <small>follower</small>
    </section>

    <section class="socialData__dataFollowers">
      <span>{{ socialNetworkDataUser.followersToday }} Today</span>
    </section>
  </article>
</template>

<script>
export default {
  name: 'PxSocialDataUser',
  props: {
    socialNetworkDataUser: {
      type: Object
    }
  }
}
</script>

<style>

</style>
